package it.eparlato.tictactoe;

public enum GameState {
	RUNNING, 
	GAME_OVER, 
	QUIT, 
	GAME_OVER_ALL_FIELDS_TAKEN, 
	GAME_OVER_A_COLUMN_HAS_BEEN_TAKEN, 
	GAME_OVER_A_ROW_HAS_BEEN_TAKEN, 
	GAME_OVER_UPPER_RIGHT_BOTTOM_LEFT_DIAGONAL, 
	GAME_OVER_UPPER_LEFT_BOTTOM_RIGHT
}
